### ISSUE TITLE
About reproducing KM-BART

### ISSUE THREAD

**Issue by getfighting** [NUSTM/VLP-MABSA#10]
Hello, I have seen some contents of KM-BART in this article. Have you ever reproduced KM-BART? I met some problems in the process of reproducing, such as the failure to find SBU data.

**Comment by getfighting** [comment]
Hello, I have seen some contents of KM-BART in this article. Have you ever reproduced KM-BART? I met some problems in the process of reproducing, such as the failure to find SBU data.

**Comment by lyhuohuo** [comment]
I did not reproduce KM-BART and just use the parameters of KM-BART to initialize our model and then perform finetuning.
