### ISSUE TITLE
Is it avaliable to public on Google Colab?

### ISSUE THREAD

**Issue by Jackson8787** [NUSTM/VLP-MABSA#13]
Hi,sorry for bothering.
I think it would be better if you put this project on Google Colab,and add link on the README.
This will make it more accessible to others and easier to reproduce the experiment.
Thanks.

**Comment by lyhuohuo** [comment]
Sorry, i'm not very familiar with Google Colab. All the code files are included in the git. You'd better perform the experiments on linux os.
