### ISSUE TITLE
预训练ValueError: invalid literal for int() with base 10: 'number'

### ISSUE THREAD

**Issue by xiaoya-Cui** [NUSTM/VLP-MABSA#33]
你好，我在预训练时出现下面错误，将17507加入ignore中也不行，请问这是数据集"senti_dir": "/data/Xya/vlp/mvsa/mvsa_photo_path.json"的问题吗？
<img width="550" alt="1710164848087" src="https://github.com/NUSTM/VLP-MABSA/assets/129070711/119c0127-f361-46ba-921b-33aa8665e5b8">

<img width="430" alt="1710164859442" src="https://github.com/NUSTM/VLP-MABSA/assets/129070711/cdc79235-8cf7-46c3-936e-c9e97c60defb">

**Comment by lyhuohuo** [comment]
可以检查一下这个文件里的路径集合是否和你当前目录路径对应

**Comment by xiaoya-Cui** [comment]
非常感谢您！确实是文件路径写错了。请问我运行了每一个预训练程序和下游任务程序，输出都是精确度这些，那AOE任务生成 的aspect/opinion在哪里呢？因为我Table2注释：MVSA数据集里面的aspect/opinion是由AOE任务生成的。非常感谢您的解答！

**Comment by lyhuohuo** [comment]
链接里应该是有的哈

**Comment by xiaoya-Cui** [comment]
再次打扰，我没有在文件夹里面找到针对数据集生成方面或情感的程序，可否详细说明？

**Comment by xiaoya-Cui** [comment]
再次打扰，我在下游任务程序里面没有找到进行下游任务推理输出 情感、命名体 或者pair的代码，可否详细说明？非常感谢！

**Comment by lyhuohuo** [comment]
相应下游任务不直接输出哈，你可以修改相应代码进行输出

**Comment by xiaoya-Cui** [comment]
好的，谢谢🙏！
