### ISSUE TITLE
关于图像特征

### ISSUE THREAD

**Issue by hxp1024** [NUSTM/VLP-MABSA#6]
你好，关于图像特征的来源，我有几个问题，希望可以解答一下
在百度网盘的微调数据集里，IJCAI2019_data/region_box/15/train文件夹下，有_att和_box两个文件夹：
1、_box文件夹下xxxx.npz是（36，4）的矩阵，是xxxx.jpg图片中36个矩形特征区域的左上角和右下角的坐标吗？
2、_att文件夹下xxxx.npz是（36，2048）的矩阵，是xxxx.jpg图片中36个矩形特征区域所对应的特征吗？2048维的特征是怎么得到的？

**Comment by lyhuohuo** [comment]
图像特征由readme里提到的Faster-RCNN方法抽取得到，具体如何实施可以查看readme中所给出的git链接。
1. _box文件夹里是36个矩形特征区域的左上角和右下角的坐标。
2. _att文件夹下为36个矩形特征区域由Fater-RCNN处理得到的ROI特征表示，为2048维。
