### ISSUE TITLE
关于复现论文结果

### ISSUE THREAD

**Issue by hxp1024** [NUSTM/VLP-MABSA#8]
你好，请想问一下，我下载数据集后，直接运行15_pretrain_full.sh 和 17_pretain_full.sh 得到的结果低于论文结果大概一个百分点，请想问一下，我是还需要修改其他地方吗？

**Comment by lyhuohuo** [comment]
可能需要调节一下训练的学习率或者随机种子，不同的机器运行会有一定差别。
